src/Entity/Campaign.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\CampaignRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;

/**
 * @ApiResource(collectionOperations={
 *          "get"={
 *              "normalization_context"={"groups"={"campaign_read"}}
 *          },
 *          "post"
 *      },
 *     itemOperations={
 *          "get"={
 *              "normalization_context"={"groups"={"campaign_details_read"}}
 *          },
 *          "put",
 *          "patch",
 *          "delete"
 *      })
 * @ApiFilter(SearchFilter::class, properties={"name" :"exact", "date_start" :"exact", "date_end" :"exact"}))
 * @ORM\Entity(repositoryClass=CampaignRepository::class)
 */
class Campaign
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"campaign_read", "campaign_details_read", "user_details_read", "status_read", "status_details_read"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"campaign_read", "campaign_details_read", "user_details_read", "status_read", "status_details_read"})
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"campaign_read", "campaign_details_read"})
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     * @Groups({"campaign_read", "campaign_details_read", "user_details_read"})
     */
    private $date_start;

    /**
     * @ORM\Column(type="date")
     * @Groups({"campaign_read", "campaign_details_read", "user_details_read"})
     */
    private $date_end;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"campaign_read", "campaign_details_read"})
     */
    private $file;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $number_tester;

    /**
     * @ORM\ManyToOne(targetEntity=Status::class, inversedBy="campaigns")
     * @Groups({"campaign_read", "campaign_details_read", "user_details_read"})
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=Session::class, mappedBy="campaign", cascade={"persist"})
     * @Groups({"campaign_read", "campaign_details_read"})
     */
    private $sessions;

    /**
     * @ORM\OneToMany(targetEntity=Question::class, mappedBy="campaign")
     * @Groups({"campaign_read", "campaign_details_read"})
     */
    private $questions;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="campaign",cascade={"persist"})
     */
    private $products;


    public function __construct()
    {
        $this->sessions = new ArrayCollection();
        $this->questions = new ArrayCollection();
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getNumberTester(): ?int
    {
        return $this->number_tester;
    }

    public function setNumberTester(int $number_tester): self
    {
        $this->number_tester = $number_tester;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->setCampaign($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->removeElement($session)) {
            // set the owning side to null (unless already changed)
            if ($session->getCampaign() === $this) {
                $session->setCampaign(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setCampaign($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getCampaign() === $this) {
                $question->setCampaign(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCampaign($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCampaign() === $this) {
                $product->setCampaign(null);
            }
        }

        return $this;
    }

    public function addStatus(Status $status): self
    {
        $this->status = $status;
        $status->setCampaign($this);

        return $this;
    }
}

src/Controller/QcmController.php
<?php

namespace App\Controller;

use App\Entity\Campaign;
use App\Entity\Question;
use App\Entity\QuestionAnswer;
use App\Form\CampaignType;
use App\Repository\CampaignRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/qcm")
 */
class QcmController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/", name="app_qcm_index", methods={"GET"})
     */
    public function index(CampaignRepository $campaignRepository): Response
    {
        return $this->render('qcm/index.html.twig', [
            'campaigns' => $campaignRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_qcm_new", methods={"GET", "POST"})
     */
    public function new(Request $request, CampaignRepository $campaignRepository): Response
    {
        $campaign = new Campaign();
        $form = $this->createForm(CampaignType::class, $campaign);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $campaignRepository->add($campaign);
            return $this->redirectToRoute('app_qcm_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('qcm/new.html.twig', [
            'campaign' => $campaign,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_qcm_show", methods={"GET"})
     */
    public function show(Campaign $campaign): Response
    {
        var_dump($campaign->getId());
        $allCurrentCampaign = $this->entityManager->getRepository(Question::class)->findAll();
        var_dump($allCurrentCampaign);
        return $this->render('qcm/show.html.twig', [
            'campaign' => $campaign,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_qcm_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Campaign $campaign, CampaignRepository $campaignRepository): Response
    {
        $form = $this->createForm(CampaignType::class, $campaign);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $campaignRepository->add($campaign);
            return $this->redirectToRoute('app_qcm_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('qcm/edit.html.twig', [
            'campaign' => $campaign,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_qcm_delete", methods={"POST"})
     */
    public function delete(Request $request, Campaign $campaign, CampaignRepository $campaignRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$campaign->getId(), $request->request->get('_token'))) {
            $campaignRepository->remove($campaign);
        }

        return $this->redirectToRoute('app_qcm_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/qcm/_delete_form.html.twig
<form method="post" action="{{ path('app_qcm_delete', {'id': campaign.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ campaign.id) }}">
    <button class="btn">Delete</button>
</form>

templates/qcm/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Campaign{% endblock %}

{% block body %}
    <h1>Edit Campaign</h1>

    {{ include('qcm/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_qcm_index') }}">back to list</a>

    {{ include('qcm/_delete_form.html.twig') }}
{% endblock %}

templates/qcm/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Campaign index{% endblock %}

{% block body %}
    <h1>Campaign index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Date_start</th>
                <th>Date_end</th>
                <th>File</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for campaign in campaigns %}
            <tr>
                <td>{{ campaign.id }}</td>
                <td>{{ campaign.name }}</td>
                <td>{{ campaign.description }}</td>
                <td>{{ campaign.dateStart ? campaign.dateStart|date('Y-m-d') : '' }}</td>
                <td>{{ campaign.dateEnd ? campaign.dateEnd|date('Y-m-d') : '' }}</td>
                <td>{{ campaign.file }}</td>
                <td>
                    <a href="{{ path('app_qcm_show', {'id': campaign.id}) }}">show</a>
                    <a href="{{ path('app_qcm_edit', {'id': campaign.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_qcm_new') }}">Create new</a>
{% endblock %}

templates/qcm/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Campaign{% endblock %}

{% block body %}
    <h1>Create new Campaign</h1>

    {{ include('qcm/_form.html.twig') }}

    <a href="{{ path('app_qcm_index') }}">back to list</a>
{% endblock %}

templates/qcm/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Campaign{% endblock %}

{% block body %}
    <h1>Campaign</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ campaign.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ campaign.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ campaign.description }}</td>
            </tr>
            <tr>
                <th>Date_start</th>
                <td>{{ campaign.dateStart ? campaign.dateStart|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_end</th>
                <td>{{ campaign.dateEnd ? campaign.dateEnd|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>File</th>
                <td>{{ campaign.file }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_qcm_index') }}">back to list</a>

    <a href="{{ path('app_qcm_edit', {'id': campaign.id}) }}">edit</a>

    {{ include('qcm/_delete_form.html.twig') }}
{% endblock %}